version: 2

sources:
  - name: raw_data_source  # Nome que você vai usar para referenciar a fonte no DBT
    description: "Fonte de dados brutos que contém as informações de item, data, ofertas e preço."
    database: "airflow_steam"  # O nome do banco de dados onde a tabela 'raw_data' está
    schema: "public"  # O esquema onde a tabela está localizada (geralmente 'public')
    tables:
      - name: raw_data_new  # Nome da tabela no banco de dados
        description: "Tabela com dados brutos de itens, ofertas e preços."
        columns:
          - name: item
            description: "Nome do item."
          - name: date
            description: "Data do registro."
          - name: offers
            description: "Número de ofertas."
          - name: price
            description: "Preço do item."
      - name: raw_data_date_buy  # Nome da tabela no banco de dados
        description: "Tabela com dados brutos de itens, ofertas e preços."
        columns:
          - name: item
            description: "Nome do item."
          - name: date_buy
            description: "Data do registro."

